#!/usr/bin/env python3
"""
# ============================================================================
# Project : Hybrid Quantum-Classical Portfolio Optimization with CVaR
#           Master's Thesis (TFM) - MSc in Quantum Computing
# Author  : Ignacio Lopez Leis
# Affil.  : Universidad Autonoma de Madrid (UAM)
# Date    : February 2026
# Module  : oos_quantum.py  (Phase 4 - OOS Quantum Estimator)
# ============================================================================
#
# Description
# -----------
# Quantum CVaR prediction for the OOS triple comparison.
# Accepts the QuantumAmplitudeEstimator instance already configured in
# the notebook (Phase 2) and delegates entirely to its
# estimate_cvar_complete method — no circuit logic is reimplemented here.
#
# A reference loss sample (typically the Monte Carlo scenarios already
# generated by oos_monte_carlo.py) is passed directly to the estimator
# so that both MC and quantum methods operate on the same N(mu_p, sigma_p²)
# model, making their predictions directly comparable.
#
# The discrete probability mass function (2^n_qubits bins) is reconstructed
# from the same loss sample using numpy to form the density_x / density_y
# fields expected by OOSPrediction and the visualization layer.
#
# All loss values use the loss convention: positive = bad.
#
# References
# ----------
# [1] Woerner & Egger (2019). Quantum Risk Analysis. npj Quantum Information.
# [2] Brassard et al. (2002). Quantum Amplitude Amplification and Estimation.
#
# License : Academic use only - TFM Project
# ============================================================================
"""

import time
import numpy as np
from typing import Any, Dict, List, Optional

# ── Passport system (BUG-005 fix) ──────────────────────────────────────────
try:
    from src.utils.passport_orchestrator import get_orchestrator
except ImportError:
    try:
        from utils.passport_orchestrator import get_orchestrator
    except ImportError:
        def get_orchestrator():
            class _D:
                def seal(self, p, **kw): return p
                def checkpoint(self, p, **kw): return p
                def assign_passport(self, *a, **kw): return None
                def link_child(self, *a): pass
            return _D()


try:
    from oos_types import OOSPrediction
except ImportError:
    from src.phase_4.oos_types import OOSPrediction

# ============================================================================
# LOGGER
# ============================================================================

try:
    from src.utils.logger import get_logger
except ImportError:
    import logging
    def get_logger(name: str = __name__) -> logging.Logger:
        _log = logging.getLogger(name)
        if not _log.handlers:
            handler = logging.FileHandler("logs/oos_quantum.txt", mode="w")
            handler.setFormatter(logging.Formatter("[%(levelname)-7s] %(message)s"))
            _log.addHandler(handler)
            _log.setLevel(logging.INFO)
        return _log

logger = get_logger(__name__)

# ============================================================================
# DISCRETE DISTRIBUTION RECONSTRUCTION
# ============================================================================

def _reconstruct_discrete_distribution(
    losses: np.ndarray,
    n_qubits: int,
) -> tuple:
    """
    Reconstruct the 2^n_qubits discrete probability mass function that the
    QuantumAmplitudeEstimator encodes as quantum amplitudes.

    This mirrors the discretization performed internally by
    QuantumCVaRCircuits._discretize_with_threshold without reimplementing
    the circuit itself. The result is used only for the density_x / density_y
    plotting fields of OOSPrediction.

    Parameters
    ----------
    losses : np.ndarray
        Shape (N,). Reference loss sample (positive = bad).
    n_qubits : int
        Number of distribution qubits used in the estimator.

    Returns
    -------
    bin_centers : np.ndarray
        Shape (2^n_qubits,). Center of each discretization bin.
    probs : np.ndarray
        Shape (2^n_qubits,). Probability mass in each bin.
    """
    n_bins = 2 ** n_qubits
    hist, edges = np.histogram(losses, bins=n_bins)
    probs = hist.astype(float)
    total = probs.sum()
    if total > 0:
        probs /= total
    bin_centers = (edges[:-1] + edges[1:]) / 2.0
    return bin_centers, probs


# ============================================================================
# QUANTUM ESTIMATOR
# ============================================================================

def estimate_quantum(
    estimator: Any,
    losses_reference: np.ndarray,
    alpha: float = 0.05,
    methods: Optional[List[str]] = None,
) -> OOSPrediction:
    """
    Predict CVaR and VaR using Quantum Amplitude Estimation.

    Delegates entirely to QuantumAmplitudeEstimator.estimate_cvar_complete,
    which is already instantiated and configured in the notebook's Phase 2
    cells. No circuit construction is performed here.

    The ``losses_reference`` array is the same Monte Carlo sample used by
    oos_monte_carlo.py so that both methods encode identical N(mu_p, sigma_p²)
    models, making the comparison scientifically sound.

    Parameters
    ----------
    estimator : QuantumAmplitudeEstimator
        Fully configured estimator instance from Phase 2. Expected interface:
        ``estimate_cvar_complete(losses, alpha, methods) -> QuantumCVaRResult``.
    losses_reference : np.ndarray
        Shape (N,). Loss scenarios in loss convention (positive = bad).
        Typically the Monte Carlo scenarios from oos_monte_carlo.py.
    alpha : float, optional
        CVaR confidence level. Default 0.05 (95% CVaR).
    methods : list of str, optional
        QAE methods to use. Default ['iqae'] (Woerner disabled by default
        in config). Passed through to estimate_cvar_complete unchanged.

    Returns
    -------
    OOSPrediction
        Prediction with method='quantum', cvar_predicted, var_predicted,
        and the 2^n_qubits discrete distribution as density_x / density_y.

    Raises
    ------
    RuntimeError
        If estimate_cvar_complete raises or returns an invalid result.
    """
    if methods is None:
        methods = ["iqae"]

    t_start = time.time()

    logger.info("=" * 60)
    logger.info("QUANTUM CVaR ESTIMATION (OOS)")
    logger.info("=" * 60)
    logger.info(
        f"methods={methods}, alpha={alpha}, "
        f"n_loss_scenarios={len(losses_reference)}, "
        f"n_qubits={getattr(estimator, 'num_distribution_qubits', '?')}"
    )

    # ------------------------------------------------------------------
    # Delegate to the existing QuantumAmplitudeEstimator
    # ------------------------------------------------------------------
    try:
        result = estimator.estimate_cvar_complete(
            losses=losses_reference,
            alpha=alpha,
            methods=methods,
        )
    except Exception as exc:
        logger.error(f"estimate_cvar_complete failed: {exc}")
        raise RuntimeError(
            f"oos_quantum.estimate_quantum: QAE estimation failed — {exc}"
        ) from exc

    # ------------------------------------------------------------------
    # Extract CVaR and VaR from QuantumCVaRResult
    # estimate_cvar_complete already works in loss convention internally
    # (cvar_estimate is a positive loss value)
    # ------------------------------------------------------------------
    cvar_loss = float(result.cvar_estimate)
    var_loss = float(result.var_estimate)

    logger.info(f"QAE CVaR_loss={cvar_loss:.6f}, VaR_loss={var_loss:.6f}")
    logger.info(
        f"Oracle queries: IQAE={result.total_oracle_queries_iqae}, "
        f"Woerner={result.total_oracle_queries_woerner}"
    )
    logger.info(
        f"Classical reference: CVaR={result.classical_cvar:.6f}, "
        f"error={result.cvar_error_vs_classical:.4f}"
    )

    # ------------------------------------------------------------------
    # Reconstruct discrete distribution for plotting
    # ------------------------------------------------------------------
    n_qubits = getattr(estimator, "num_distribution_qubits", 4)
    bin_centers, probs = _reconstruct_discrete_distribution(
        losses=losses_reference,
        n_qubits=n_qubits,
    )

    execution_time_s = time.time() - t_start
    logger.info(f"Quantum OOS estimation completed in {execution_time_s:.4f}s")

    # ------------------------------------------------------------------
    # Build metadata from QuantumCVaRResult fields
    # ------------------------------------------------------------------
    metadata: Dict[str, Any] = {
        "methods":                      methods,
        "alpha":                        float(alpha),
        "n_qubits":                     n_qubits,
        "n_bins":                       2 ** n_qubits,
        "n_loss_scenarios":             len(losses_reference),
        "total_oracle_queries_iqae":    int(result.total_oracle_queries_iqae),
        "total_oracle_queries_woerner": int(result.total_oracle_queries_woerner),
        "total_circuits_executed":      int(result.total_circuits_executed),
        "qae_execution_time_ms":        float(result.execution_time_ms),
        "classical_cvar_reference":     float(result.classical_cvar),
        "cvar_error_vs_classical":      float(result.cvar_error_vs_classical),
        "tail_probability":             float(result.tail_probability),
        "zne_applied":                  bool(result.zne_applied),
        "zne_improvement":              float(result.zne_improvement),
    }

    return OOSPrediction(
        method="quantum",
        cvar_predicted=cvar_loss,
        var_predicted=var_loss,
        density_x=bin_centers,
        density_y=probs,
        execution_time_s=execution_time_s,
        metadata=metadata,
    )


# ============================================================================
# EXPORTS
# ============================================================================

__all__ = [
    "estimate_quantum",
]
