"""
gen_zne_tables.py — LaTeX artefacts for the Sec. 7.2 ZNE analysis
=================================================================
Reads results/hardware_validation/sim_zne_compare_latest.json and emits, into
results/paper_tables/:

  tab_zne_compare.tex   the booktabs comparison table (raw / global / gate / FIIM
                        x E1/E2/E3), with depth, raw bias and ZNE bias columns.
  zne_macros.tex        \newcommand macros with the inline numbers used in the
                        body text, so prose never hard-codes a figure.

Run AFTER hw_sim_zne_compare.py. Numbers are deterministic (seed = 42), so the
regenerated artefacts match the values quoted in the manuscript exactly.

Usage
-----
    python scripts/gen_zne_tables.py
"""

import json
from pathlib import Path

ROOT    = Path(__file__).resolve().parent.parent
IN_JSON = ROOT / "results" / "hardware_validation" / "sim_zne_compare_latest.json"
OUT_DIR = ROOT / "results" / "paper_tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)

COND_LABEL = {
    "raw":         r"Raw ($\lambda=1$)",
    "global_fold": r"Global fold",
    "gate_fold":   r"Gate fold",
    "iim_fiim":    r"Identity insertion (FIIM)",
}
SCALES = ["1.0", "3.0", "5.0"]


def _fmt(x, nd=4):
    return f"{x:.{nd}f}"


def build_table(d):
    comp = d["comparison"]
    noises = list(d["metadata"]["noise_levels"].keys())
    p2q = d["metadata"]["noise_levels"]

    lines = [
        r"% Auto-generated by scripts/gen_zne_tables.py -- do not edit by hand.",
        r"\begin{table}[!t]",
        r"  \centering",
        r"  \small",
        r"  \caption{ZNE methods on IQM IQAE in the \code{qiskit-aer} depolarising "
        r"noise model ($m=1$ circuit, $p_{\mathrm{th}}=" + _fmt(d["metadata"]["p_theory_m1"]) +
        r"$, 4096 shots, 3 replicas, seed 42). Depth is the post-transpile depth at "
        r"\code{opt\_level=0} for $\lambda\in\{1,3,5\}$. $\Delta_{\mathrm{raw}}$ is the "
        r"bias of the raw $\lambda=1$ estimate; $\Delta_{\mathrm{ZNE}}$ is the bias of "
        r"the Richardson-extrapolated estimate. Identity insertion attains the lowest "
        r"depth overhead; below the aliasing threshold the raw estimate is not improved "
        r"by any extrapolation method.}",
        r"  \label{tab:zne_compare}",
        r"  \begin{tabular}{llrrrr}",
        r"    \toprule",
        r"    Method & Noise & depth$_{1,3,5}$ & $\Delta_{\mathrm{raw}}$ & "
        r"$\Delta_{\mathrm{ZNE}}$ & raw best? \\",
        r"    \midrule",
    ]

    for cond in ["global_fold", "gate_fold", "iim_fiim"]:
        for k, nl in enumerate(noises):
            e = comp[nl][cond]
            sr = e["scale_results"]
            depths = ",".join(str(sr[s]["depth_actual"]) for s in SCALES)
            braw = sr["1.0"]["bias_raw"]
            bzne = e["bias_zne_richardson"]
            rawbest = r"\checkmark" if e["raw_better_than_zne"] else r"---"
            method = COND_LABEL[cond] if k == 0 else ""
            lines.append(
                f"    {method} & {nl} ($p_{{2q}}={p2q[nl]:g}$) & ${depths}$ & "
                f"${_fmt(braw)}$ & ${_fmt(bzne)}$ & {rawbest} \\\\"
            )
        lines.append(r"    \midrule")
    # raw reference row
    raw_bias = [comp[nl]["raw"]["scale_results"]["1.0"]["bias_raw"] for nl in noises]
    rb = ", ".join(f"{nl}:{_fmt(b,4)}" for nl, b in zip(noises, raw_bias))
    lines.append(
        r"    \multicolumn{6}{l}{\footnotesize Raw $\lambda=1$ bias by noise: "
        + rb + r"} \\"
    )
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def build_macros(d):
    comp = d["comparison"]
    noises = list(d["metadata"]["noise_levels"].keys())
    hi = noises[-1]

    g = comp[hi]["global_fold"]["scale_results"]
    f = comp[hi]["iim_fiim"]["scale_results"]

    def cmd(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    m = [
        r"% Auto-generated by scripts/gen_zne_tables.py -- inline ZNE numbers.",
        cmd("zneBaseDepth", d["metadata"]["base_depth_opt1"]),
        cmd("zneGlobalDepthFive", g["5.0"]["depth_actual"]),
        cmd("zneFIIMDepthFive",   f["5.0"]["depth_actual"]),
        cmd("zneRawBiasLow",  _fmt(comp[noises[0]]["raw"]["scale_results"]["1.0"]["bias_raw"])),
        cmd("zneRawBiasHigh", _fmt(comp[hi]["raw"]["scale_results"]["1.0"]["bias_raw"])),
        cmd("zneFIIMBiasHigh", _fmt(comp[hi]["iim_fiim"]["bias_zne_richardson"])),
        cmd("zneGlobalBiasHigh", _fmt(comp[hi]["global_fold"]["bias_zne_richardson"])),
        "",
    ]
    return "\n".join(m)


def main():
    if not IN_JSON.exists():
        raise SystemExit(f"Missing {IN_JSON}. Run scripts/hw_sim_zne_compare.py first.")
    d = json.loads(IN_JSON.read_text())
    (OUT_DIR / "tab_zne_compare.tex").write_text(build_table(d))
    (OUT_DIR / "zne_macros.tex").write_text(build_macros(d))
    print(f"saved -> {OUT_DIR / 'tab_zne_compare.tex'}")
    print(f"saved -> {OUT_DIR / 'zne_macros.tex'}")


if __name__ == "__main__":
    main()
